[workspace]
authors = ["Yu-An Chen <atwood12@gmail.com>"]
channels = ["conda-forge"]
name = "pixi-env"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
pip = ">=25.2,<26"
openjdk = ">=21,<22"
pyqt = ">=5.15.11,<6"
asciitree = ">=0.3.3,<0.4"
fire = "0.5.0.*"

[pypi-dependencies]
ashlar = { path = "..", editable = true }
